### ISSUE TITLE
Code not running

### ISSUE THREAD

**Issue by edneibach** [philipperemy/Stanford-NER-Python#1]
Hello. These bindings seem very interesting and i really want to use them, but i am a beginner with Python and Github and don`t know if i did something wrong. Maybe i`m using the wrong version of java/python?
This is what it`s giving me:

Executing command = cd stanford-ner; java.exe -mx1g -cp "*:lib/*" edu.stanford.nlp.ie.NERClassifierCombiner -ner.model classifiers/english.all.3class.distsim.crf.ser.gz -outputFormat tabbedEntities -textFile ../samples.txt > ../out.txt
Traceback (most recent call last):
  File "main.py", line 127, in <module>
    exit(main(argv))
  File "main.py", line 122, in main
    entities = stanford_ner(filename, verbose)
  File "main.py", line 87, in stanford_ner
    assert not java_process.returncode, 'ERROR: Call to stanford_ner exited with a non-zero code status.'
AssertionError: ERROR: Call to stanford_ner exited with a non-zero code status.

I'm running the latest java version and python 3.8, on Windows. Any help would be immensely appreciated.

**Comment by philipperemy** [comment]
I'm not sure if it works well on Windows. Can you try this on Linux/Ubuntu? Or even on a virtualbox with Ubuntu installed?

**Comment by philipperemy** [comment]
I'll close this issue for now. The most likely problem is that you're running on Windows.
